---
title: "EDS-221-Day4"
format: html
editor: visual
---

## Writing functions

```{r}
 temp_f_to_c <- function(f){ 
   temp_in_degree = (5/9)*(f-32)
   print(temp_in_degree)
 }
 
temp_f_to_c(100)
```

```{r}
intro <- function(hometown, age){
  paste0("I am ", as.numeric(age), " and I am from ", as.character(hometown))
}

intro(hometown= "Nepal", 22)
```

Functions with conditions\
Calculate animals age

```{r}
animal_age <- function(species, age){
  if(species=="Dog"){
    age * 7
  } else if (species=="goat") {
    age * 10
  } else {
   "please enter only limited animal names bro" 
  }
}

animal_age("whale", 20)
```

```{r}
correct_metric <- function(metrics, temp){
  if(metrics == "metric"){
    temp
  } else if(metrics == "english"){
    (temp * (9/5))+ 32
  }
}

correct_metric(metrics = "english", 20 )
```

More functions

```{r}
library(tidyverse)
choice <- data.frame(dog_name = c("sujan", "Sabin", "Prakash"),
                     dog_choice = c("Buff", "momo", "chowmein"))
```

```{r}
dog_menu <- function(enter_dog_name){
            subset <- filter(choice , dog_name == enter_dog_name)
            filter(choice , dog_name == enter_dog_name)
}

dog_menu(enter_dog_name="Sujan")
```

For loop

```{r}
df_means <- function(df){
  for(i in seq_along(df)){
    col_mean = mean(df[[i]], na.rm=TRUE)
    col_name = colnames(df[i])
    print(paste("The mean value of", col_name, "is" , col_mean))
  }
}
```

```{r}
df_means(mtcars)
```
